// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIjsDTs0OLohsp6HdLTJJ84vyAnLkdOwI',
    appId: '1:297475681366:web:46ffbf7f92993d1fa39ff7',
    messagingSenderId: '297475681366',
    projectId: 'my-pfe-sany',
    authDomain: 'my-pfe-sany.firebaseapp.com',
    storageBucket: 'my-pfe-sany.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdIzRuAmWs3-2K7dSoYVSvCBA1AwciGwo',
    appId: '1:297475681366:android:dbeb641df624ba9da39ff7',
    messagingSenderId: '297475681366',
    projectId: 'my-pfe-sany',
    storageBucket: 'my-pfe-sany.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGDPmQvqtiPFKgEv9RIvNjx088V6QBxrk',
    appId: '1:297475681366:ios:b5d6afc128e13ea6a39ff7',
    messagingSenderId: '297475681366',
    projectId: 'my-pfe-sany',
    storageBucket: 'my-pfe-sany.appspot.com',
    iosClientId: '297475681366-h9m9tiu0f6tbnhjcp25nul28cfkgnuc7.apps.googleusercontent.com',
    iosBundleId: 'com.pfe.sany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGDPmQvqtiPFKgEv9RIvNjx088V6QBxrk',
    appId: '1:297475681366:ios:ff8570448f9d117ba39ff7',
    messagingSenderId: '297475681366',
    projectId: 'my-pfe-sany',
    storageBucket: 'my-pfe-sany.appspot.com',
    iosClientId: '297475681366-gtem4kbn2njdoetkv2jmj4bmm7th697h.apps.googleusercontent.com',
    iosBundleId: 'com.pfe.sany.RunnerTests',
  );
}
