// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRcMfvrtQRjca2pGIcbc_9jcyZQFsRVgY',
    appId: '1:715642753599:web:a330626e16435a2dff9e8a',
    messagingSenderId: '715642753599',
    projectId: 'pfe-sany',
    authDomain: 'pfe-sany.firebaseapp.com',
    storageBucket: 'pfe-sany.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxRiq0z_LCF5_aNV2tRJQV5w2PcHFkDZg',
    appId: '1:715642753599:android:f4804bb7f39a201cff9e8a',
    messagingSenderId: '715642753599',
    projectId: 'pfe-sany',
    storageBucket: 'pfe-sany.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZUZHjLJkltNVxDLF5Nf1s8tnSnOWS0Og',
    appId: '1:715642753599:ios:6b2ff622126724b4ff9e8a',
    messagingSenderId: '715642753599',
    projectId: 'pfe-sany',
    storageBucket: 'pfe-sany.appspot.com',
    iosClientId: '715642753599-lc0u0745714gpvpblopsieg0m9vg1ohu.apps.googleusercontent.com',
    iosBundleId: 'com.pfe.sany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZUZHjLJkltNVxDLF5Nf1s8tnSnOWS0Og',
    appId: '1:715642753599:ios:18906e4a269bcb52ff9e8a',
    messagingSenderId: '715642753599',
    projectId: 'pfe-sany',
    storageBucket: 'pfe-sany.appspot.com',
    iosClientId: '715642753599-fo9e9dqtcn1vt17rqoqv0nft453snsm3.apps.googleusercontent.com',
    iosBundleId: 'com.pfe.sany.RunnerTests',
  );
}
